TRAIN:
  MANUAL_SEED: 1
  CONV_REPEATABLE: true
  BATCH_SIZE: 32
  EPOCH: 101
  OPTIMIZER: adam
  LR: 0.0001
  SCHEDULER: StepLR
  LR_DECAY_GAMMA: 0.1
  LR_DECAY_STEP:
  - 70
  LOG_INTERVAL: 10
  FIND_UNUSED_PARAMETERS: false
  GRAD_CLIP_ENABLED: true
  GRAD_CLIP:
    TYPE: 2
    NORM: 1.0
  WEIGHT_DECAY: 0.0
DATASET:
  TRAIN:
    TYPE: DexYCBMultiView
    DATA_MODE: 3D
    DATA_ROOT: ./data
    DATA_SPLIT: train
    N_VIEWS: 8
    SETUP: s0
    USE_LEFT_HAND: false
    FILTER_INVISIBLE_HAND: true
    MASTER_SYSTEM: as_constant_camera
    TRANSFORM:
      TYPE: SimpleTransform3DMultiView
      AUG: true
      CENTER_JIT: 0.0
      SCALE_JIT: 0.06
      ROT_JIT: 5
      COLOR_JIT: 0.3
      ROT_PROB: 0.5
      OCCLUSION: true
      OCCLUSION_PROB: 0.2
  TEST:
    TYPE: DexYCBMultiView
    DATA_MODE: 3D
    DATA_ROOT: ./data
    DATA_SPLIT: test
    N_VIEWS: 8
    SETUP: s0
    USE_LEFT_HAND: false
    FILTER_INVISIBLE_HAND: true
    TEST_WITH_MULTIVIEW: true
    MASTER_SYSTEM: as_constant_camera
    TRANSFORM:
      TYPE: SimpleTransform3DMultiView
      AUG: false
DATA_PRESET:
  USE_CACHE: true
  BBOX_EXPAND_RATIO: 2.0
  IMAGE_SIZE:
  - 256
  - 256
  CENTER_IDX: 0
  NUM_JOINTS: 21
  NUM_VERTS: 778
MODEL:
  TYPE: MVP
  PRETRAINED: null
  USE_DOWNSAMPLED_VERTICES: false
  BACKBONE:
    TYPE: ResNet34
    PRETRAINED: true
    FREEZE_BATCHNORM: true
  HEAD:
    TYPE: MVPHead
    FEAT_SIZE:
    - 512
    - 256
    - 128
    - 64
    DECODER:
      IMAGE_SIZE:
      - 256
      - 256
      CAMERA_NUM: 8
      d_model: 256
      dim_feedforward: 1024
      dropout: 0.1
      activation: relu
      num_feature_levels: 1
      nhead: 8
      dec_n_points: 4
      detach_refpoints_cameraprj_firstlayer: true
      fuse_view_feats: cat_proj
      projattn_posembed_mode: use_rayconv
      num_decoder_layers: 6
      return_intermediate_dec: true
    MANO_POSE_NCOMPS: 15
    NUM_QUERY: 21
    NUM_PREDS: 6
    NUM_REG_FCS: 2
    CENTER_IDX: 0
    DEPTH_NUM: 64
    POSITION_RANGE:
    - -1.2
    - -1.2
    - 0.2
    - 1.2
    - 1.2
    - 2.0
    LID: true
    DEPTH_START: 0.2
    DEPTH_END: 2.0
    EMBED_DIMS: 256
    IN_CHANNELS: 128
  LOSS:
    JOINTS_LOSS_TYPE: l2
    VERTICES_LOSS_TYPE: l1
    USE_MESH_REGRESSION_JOINT: true
    JOINTS_LOSS_WEIGHT: 1.0
    VERTICES_LOSS_WEIGHT: 1.0
    JOINTS_2D_LOSS_WEIGHT: 1.0
    VERTICES_2D_LOSS_WEIGHT: 1.0
    EDGE_LOSS_WEIGHT: 0.0
