DATASET:
  TEST:
    TYPE: DexYCBMultiView_CMR
    DATA_MODE: 3D
    DATA_ROOT: ./data
    DATA_SPLIT: test
    N_VIEWS: 8
    SETUP: s0
    USE_LEFT_HAND: False
    FILTER_INVISIBLE_HAND: True
    TEST_WITH_MULTIVIEW: True
    MASTER_SYSTEM: as_constant_camera

    TRANSFORM:
      TYPE: SimpleTransform3DMultiView
      AUG: False

DATA_PRESET:
  USE_CACHE: True
  BBOX_EXPAND_RATIO: 2.0
  IMAGE_SIZE: [256, 256]
  CENTER_IDX: 0
  NUM_JOINTS: 21
  WITH_MASK: True

MODEL:
  TYPE: CMR_G
  PRETRAINED: null
  IN_CHANNELS: 3
  OUT_CHANNELS: [64, 128, 256, 512]
  BACKBONE: ResNet18
  ATT: false
  METRIC:
    TYPE: PAEval
    MESH_SCORE: True

TRAIN:
  MANUAL_SEED: 1
  CONV_REPEATABLE: True
  BATCH_SIZE: 1
  EPOCH: 100
  OPTIMIZER: adam
  LR: 0.0001
  SCHEDULER: StepLR
  LR_DECAY_STEP: [70]
  LR_DECAY_GAMMA: 0.1
  WEIGHT_DECAY: 0.0
  FIND_UNUSED_PARAMETERS: False
  LOG_INTERVAL: 10
  GRAD_CLIP_ENABLED: True
  GRAD_CLIP:
    NORM: 1.0
    TYPE: 2
